version: "4"
services:
  django:
    build: ./autoseviceSQL
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./autoseviceSQL:/usr/src/app
    depends_on:
      - pgdb

  my_redis:
    image: redis
    ports:
      - 6379:6379
  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data

volumes:
  pgdbdata: null
